require("user.options")
require("user.keybindings")
require("user.plugins")
require("user.autocommands")

require("user.telescope")
require("user.treesitter")
require("user.lualine")
require("user.whichkey")
require("user.comment")
require("user.indent")
require("user.copilot")
require("user.ufo")
require("user.lsp")
require("user.nvim_tree")
require("user.spider")
require("user.notify")
require("user.noice")
require("user.harpoon")
require("user.flash")

vim.cmd "colorscheme monokai"
