require("user.options")
require("user.keybindings")
require("user.plugins")
require("user.autocommands")

--require("user.bufferline")
require("user.telescope")
require("user.lualine")
require("user.whichkey")
require("user.comment")
require("user.indent")
--require("user.autopairs")
require("user.copilot")
require("user.ufo")
require("user.lsp")
require("user.nvim_tree")
require("user.spider")
require("user.notify")

vim.cmd "colorscheme monokai"
